### PR TITLE
FIX: Improve error handling

### LINKED ISSUE #71: jobs never complete if studio has an internal error
When the studio encounters an internal error (on the Python side) while processing a job, the job status pane keeps the job as "active" indefinitely. It'd be great to handle this sort of issue (if feasible) on the client side so that it can be reported to users, because it isn't clear right now that the server errored (I thought I just had a long-running job). This is analogous to an internal server error (status code 500) being reported to website users.

Here's some example output for the specific issue I ran into (which I'm about to fix, but it may help illustrate where this could be handled):

```
[1] API: 127.0.0.1 - - [2016-08-31 12:44:50] "OPTIONS /api/jobs/5834205a-ebf2-45e2-9f3c-af2c3be6bfe9 HTTP/1.1" 200 330 0.001631
[1] API: 127.0.0.1 - - [2016-08-31 12:44:50] "GET /api/jobs/5834205a-ebf2-45e2-9f3c-af2c3be6bfe9 HTTP/1.1" 200 3682 0.002653
[1] API (error): ERROR:concurrent.futures:exception calling callback for <Future at 0x11127d1d0 state=finished returned Results>
[1] Traceback (most recent call last):
[1]   File "/Users/jairideout/miniconda3/envs/qiime2/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
[1]     callback(self)
[1]   File "/Users/jairideout/dev/qiime2/qiime-studio/qiime_studio/api/jobs.py", line 153, in callback
[1]     result.save(path)
[1] AttributeError: 'Results' object has no attribute 'save'
[1] API: 127.0.0.1 - - [2016-08-31 12:44:51] "GET /api/jobs/5834205a-ebf2-45e2-9f3c-af2c3be6bfe9 HTTP/1.1" 200 3682 0.001878
[1] API: 127.0.0.1 - - [2016-08-31 12:44:52] "GET /api/jobs/5834205a-ebf2-45e2-9f3c-af2c3be6bfe9 HTTP/1.1" 200 3682 0.001785
[1] API: 127.0.0.1 - - [2016-08-31 12:44:53] "GET /api/jobs/5834205a-ebf2-45e2-9f3c-af2c3be6bfe9 HTTP/1.1" 200 3682 0.001880
```

### PR DESCRIPTION
**Pull request by jakereps**
I think I covered every place that was previously open to errors. To stop `try:except:` redundancy I just made it into a decorator.

Fixes #71

### CODE REVIEW

**Comment by jairideout** [comment]
Awesome, thanks @jakereps! @ebolyen, can you review b/c you're familiar with the codebase?

**Comment by thermokarst** [comment]
Thanks @jakereps! Do you think it makes sense to return status code 400 everywhere? If not, maybe we can take advantage this [proposed API Exception pattern](http://flask.pocoo.org/docs/0.11/patterns/apierrors/), and handle specific errors like this:
```python
raise InvalidUsage('This view is gone', status_code=410)
```

**Comment by jakereps** [comment]
I'm not actually sure. I know some of the status codes aren't exact, but these (this PR specifically) kind of seem more like 500s as the example @jairideout posted was the server failing because of a QIIME 2 API issue within the REST API. The JS/UI fetch response we have set only uses `if (!response.ok)` or something which only looks if it's in the 200s, so as of now changing them wouldn't really make any difference functionality-wise. Could definitely be something during the refactor (I think a UI overhaul is coming, and now with a little more React experience better Component-ization of the code).

This was just moving the existing `try:except:`s wholesale to a decorator.

**Comment by thermokarst** [comment]
Ah! I forgot that the client app isn't up to speed on error handling. The decorator seems like a good stopgap for now. I agree that an overhaul would be beneficial (and in particular, some time spent on error handling server-side and client-side).

I did a quick check, recreating the issue reported in #71, and I am still seeing the neverending job situation here. At first glance, it looks like any exceptions occurring in the async callback factory aren't being reraised/handled appropriately. I am not familiar enough with that functionality to say for sure without looking into it more closely, but it looks like we need to add a check for any [exceptions](https://docs.python.org/3/library/asyncio-task.html#asyncio.Future.exception) that have been raised in the `Future`, which is going to require a slightly different approach than the decorator (I think).

**Comment by jakereps** [comment]
Yeah looks like that specific issue happened here, which isn't protected: 

https://github.com/qiime2/qiime-studio/blob/master/qiime_studio/api/jobs.py#L151-L154

I can't get it to reproduce even with the current master of QIIME 2 though. Do you or @jairideout have a way to guarantee a failure? I have the QIIME 2 master installed and have just been trying random methods, mainly rarefy, and they all work.

**Comment by thermokarst** [comment]
Call a bogus method on result.

**Comment by thermokarst** [comment]
I realized I linked to the wrong 'Future' above, I think this is the [appropriate one here](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Future.add_done_callback). Worth noting:

> If the callable raises an Exception subclass, it will be logged and ignored. If the callable raises a BaseException subclass, the behavior is undefined.

This is exactly the behavior that @jairideout noted in #71.

**Comment by jairideout** [comment]
@jakereps are you able to reproduce the NeverEnding Story I encountered?

**Comment by jakereps** [comment]
@jairideout I hadn't yet. I'll check it out today though. I was just running with the master Q2 branch,  but didn't try putting a guaranteed failure within the callback yet.

**Comment by jairideout** [comment]
Sounds good @jakereps!
giphy

**Comment by jakereps** [comment]
Should be good.

**Comment by thermokarst** [comment]
Looks great @jakereps!  Thanks for knocking this one out. 
sirocco

**Comment by jairideout** [comment]
Thanks @jakereps and @thermokarst!

**Pull request merged**
